define([], function() {
  return {
    "PropertyPaneDescription": "Descripción",
    "BasicGroupName": "Nombre del Grupo",
    "DescriptionFieldLabel": "Campo de Descripción",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en su entorno local como elemento web de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en su entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en su entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en su entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "camposObligatoriosTitle": "Debe ingresar todos los campos marcados con (*)",

    // Srsc.tsx
    "ReservaSalaView": "Reserva Sala",
    "SalasDisponiblesView": "Salas Disponibles",
    "BloqueoSalaView": "Bloqueo Sala",
    "GenerarQRView": "Generar QR",
    "ReportesView": "Reportes",
    "MisReservasView": "Mis Reservas",

    // ReservaSala.tsx
    "ReservaSalaTitle": "Reserva de Sala",
    "LoadingConfig": "Cargando configuración...",
    "PlantaLabel": "División",
    "SelectPlantaPlaceholder": "Seleccione una división",
    "PisoLabel": "Piso",
    "SelectPisoPlaceholder": "Seleccione un piso",
    "UsuarioLabel": "Usuario",
    "SelectUsuarioPlaceholder": "Seleccione un usuario",
    "FechaReservaLabel": "Fecha de Reserva",
    "SelectFechaReservaPlaceholder": "Seleccione una fecha...",
    "PlanoPisoTitle": "Plano del Piso",
    "SelectPlantaPisoFechaAvailability": "Seleccione división, piso y fecha para ver disponibilidad",
    "ViewHorariosFor": "Ver horarios para ",
    "SelectPlantaPisoFechaSalaWarning": "Por favor, seleccione División, Piso y Fecha antes de seleccionar una sala.",
    "ErrorLoadingFilterOptions": "Error al cargar las opciones de filtro.",
    "ErrorLoadingSalasForPiso": "Error al cargar las salas para el piso ",
    "ErrorLoadingHorariosForSala": "Error al cargar los horarios para la sala ",
    "MissingReservationData": "Faltan datos para la reserva.",
    "ReservationConfirmedSuccess": "¡Reserva confirmada con éxito!",
    "ReservationConfirmError": "Hubo un error al confirmar la reserva. Por favor, intente de nuevo.",

    // SalasDisponibles.tsx
    "SalasDisponiblesTitle": "Salas Disponibles",
    "LoadingFilters": "Cargando filtros...",
    "NoAvailableRoomsForDate": "No hay salas con horarios disponibles en este piso para la fecha seleccionada.",
    "NoPisosConfiguredForPlanta": "No hay pisos configurados para esta división.",
    "SelectPlantaToViewPisos": "Seleccione una división para ver los pisos.",
    "PisoColumn": "Piso",
    "SalaColumn": "Sala",
    "CapacidadColumn": "Capacidad",
    "HorasDisponiblesColumn": "Horas Disponibles",
    "AccionesColumn": "Acciones",
    "ViewDetailAndReserveRoom": "Ver detalle y reservar sala",
    "ReserveButton": "Reservar",
    "SelectPlantaUsuarioFechaReserveWarning": "Por favor, seleccione División, Usuario y Fecha antes de reservar una sala.",
    "ErrorLoadingAvailableRoomsForPiso": "Error al cargar las salas disponibles para el piso ",
    "LoadingSalasFor": "Cargando salas para ",

    // BloqueoSala.tsx
    "BloqueoSalaTitle": "Bloqueo de Sala",
    "FechaBloqueoLabel": "Fecha de Bloqueo",
    "SelectFechaBloqueoPlaceholder": "Seleccione una fecha...",
    "SelectPlantaPisoUsuarioFechaBlockWarning": "Seleccione división, piso, usuario y fecha para bloquear sala",
    "BlockRoom": "Bloquear sala ",
    "ConfirmBloqueoSalaTitle": "Confirmar Bloqueo de Sala",
    "ComentarioBloqueoLabel": "Comentario de Bloqueo",
    "ComentarioBloqueoPlaceholder": "Ingrese el motivo del bloqueo...",
    "ConfirmBloqueoButton": "Confirmar Bloqueo",
    "CancelButton": "Cancelar",
    "CompleteAllFieldsBlockWarning": "Por favor, complete todos los campos para el bloqueo.",
    "RoomBlockedSuccess": "¡Sala bloqueada con éxito!",
    "RoomBlockError": "Hubo un error al bloquear la sala. Por favor, intente de nuevo.",

    // ReservaSalaSchedule.tsx
    "ReservationDetailsTitle": "Detalles de Reserva",
    "FechaNotSelected": "Fecha no seleccionada",
    "LoadingHorarios": "Cargando horarios...",
    "NoHorariosAvailable": "No hay horarios disponibles para esta sala en la fecha seleccionada.",
    "HorasDisponiblesTable": "Horas disponibles",
    "DisponibilidadTable": "Disponibilidad",
    "ReservadoPorTable": "Reservado por",
    "ReservedStatus": "Reservado",
    "NotAvailableStatus": "No Disponible",
    "NoReservationStatus": "Sin Reserva",
    "AvailableStatus": "Disponible",
    "NAStatus": "N/A",
    "AsistentesPeoplePicker": "Asistentes",
    "ConfirmReservationButton": "Confirmar Reserva",
    "CloseButton": "Cerrar",

    //MisReservas.tsx
    "MisReservasTitle": "Mis Reservas",
    "ReservaEliminadaSuccess": "Reserva eliminada con éxito.",
    "ReservaEliminadaError": "Error al eliminar la reserva.",
    "DeleteReservationButton": "Eliminar Reserva",

    // Reportes.tsx 
    "ReportesTitle": "Reporte de Reservas y Bloqueos",
    
    "AllPlaceholder": "Todas",
    "FechaDesdeLabel": "Fecha Desde",
    "FechaHastaLabel": "Fecha Hasta",
    "SearchButton": "Buscar",
    "ExportToCSVButton": "Exportar a CSV",
    "ErrorLoadingReport": "Error al cargar el reporte. Por favor, intente de nuevo.",
    "LoadingReport": "Cargando reporte...",
    "NoResultsFound": "No se encontraron resultados para los filtros seleccionados.",
    "SalaReservadaColumn": "Sala Reservada",
    "FechaReservaColumn": "Fecha Reserva",
    "FechaTerminoReservaColumn": "Fecha Término Reserva",
    "BloqueHorarioColumn": "Bloque Horario",
    "EstadoColumn": "Estado",
    "FechaCheckInColumn": "Fecha Check-In",
    "FechaCheckOutColumn": "Fecha Check-Out",
    "KPIColumn": "KPI",
    "VerColumn": "Ver",
    "EliminarColumn": "Eliminar",
    "ViewDetailsButton": "Ver Detalles",

    // Mantenedores
    "MantenedorView": "Mantenedores",
    "MantenedorHorariosView": "Mantenedor Horarios",
    "MantenedorUsuariosView": "Mantenedor Usuarios",
    "MantenedorSalasView": "Mantenedor Salas",
    "MantenedorPisosView": "Mantenedor Pisos",

    // MantenedorSalas.tsx
    "MantenedorSalasTitle": "Mantenedor de Salas",
    "AddSalaButton": "Agregar Sala",
    "EditSalaButton": "Editar Sala",
    "VerQR": "Ver QR",
    "DeleteSalaButton": "Eliminar Sala",
    "SalaNameLabel": "Nombre de la Sala",
    "SalaCupoLabel": "Cupo",
    "SalaPisoLabel": "Piso",
    "SalaCoordinatesLabel": "Coordenadas (X,Y)",
    "SalaActiveLabel": "Activa",
    "SelectPisoFilterPlaceholder": "Filtrar por Piso",
    "SelectPlantaFilterPlaceholder": "Filtrar por División",
    "NoSalasFound": "No se encontraron salas.",
    "ConfirmDeleteSala": "¿Está seguro que desea eliminar la sala {0}?",
    "SalaAddedSuccess": "Sala agregada con éxito.",
    "SalaUpdatedSuccess": "Sala actualizada con éxito.",
    "SalaDeletedSuccess": "Sala eliminada con éxito.",
    "ErrorAddingSala": "Error al agregar la sala.",
    "ErrorUpdatingSala": "Error al actualizar la sala.",
    "ErrorDeletingSala": "Error al eliminar la sala.",
    "ErrorFetchingSalas": "Error al cargar las salas.",
    "ErrorFetchingPisos": "Error al cargar los pisos.",
    "LoadingSalas": "Cargando salas...",
    "LoadingPisos": "Cargando pisos...",
    "SaveButton": "Guardar",
    "RequiredField": "Este campo es requerido.",
    "InvalidNumber": "Debe ser un número válido.",
    "InvalidCoordinates": "Debe marcar una zona en el plano.",
    "HorariosLabel": "Horarios",
    "SelectAllHorasLabel": "Marcar todos", 
    "CannotDeleteSalaWithoutId": "No se puede eliminar una sala sin ID.",

    // Mantenedor Vicepresidencias
    "MantenedorVicepresidenciasView": "Mantenedor Vicepresidencias",
    "ErrorFetchingVicepresidencias": "Error al cargar las vicepresidencias.",
    "ConfirmDeleteVicepresidencia": "¿Está seguro que desea eliminar la vicepresidencia {0}?",
    "VicepresidenciaDeletedSuccess": "Vicepresidencia eliminada con éxito.",
    "ErrorDeletingVicepresidencia": "Error al eliminar la vicepresidencia.",
    "FormErrorsWarning": "Por favor, corrija los errores del formulario.",
    "VicepresidenciaUpdatedSuccess": "Vicepresidencia actualizada con éxito.",
    "VicepresidenciaAddedSuccess": "Vicepresidencia agregada con éxito.",
    "ErrorUpdatingVicepresidencia": "Error al actualizar la vicepresidencia.",
    "ErrorAddingVicepresidencia": "Error al agregar la vicepresidencia.",
    "CannotDeleteWithoutId": "No se puede eliminar una vicepresidencia sin ID.",
    "VicepresidenciaNameLabel": "Nombre de la Vicepresidencia",
    "VicepresidenciaActiveLabel": "Activa",
    "YesLabel": "Sí",
    "NoLabel": "No",
    "EditVicepresidenciaButton": "Editar Vicepresidencia",
    "DeleteVicepresidenciaButton": "Eliminar Vicepresidencia",
    "AddVicepresidenciaButton": "Agregar Vicepresidencia",
    "LoadingVicepresidencias": "Cargando vicepresidencias...",
    "NoVicepresidenciasFound": "No se encontraron vicepresidencias.",

    // Mantenedor Gerencia
    "MantenedorGerenciaView": "Mantenedor Gerencia",
    "ErrorFetchingGerencias": "Error al cargar las gerencias.",
    "ConfirmDeleteGerencia": "¿Está seguro que desea eliminar la gerencia {0}?",
    "GerenciaDeletedSuccess": "Gerencia eliminada con éxito.",
    "ErrorDeletingGerencia": "Error al eliminar la gerencia.",
    "ErrorUpdatingGerencia": "Error al actualizar la gerencia.",
    "ErrorAddingGerencia": "Error al agregar la gerencia.",
    "GerenciaUpdatedSuccess": "Gerencia actualizada con éxito.",
    "GerenciaAddedSuccess": "Gerencia agregada con éxito.",
    "CannotDeleteGerenciaWithoutId": "No se puede eliminar una gerencia sin ID.",
    "GerenciaNameLabel": "Nombre de la Gerencia",
    "GerenciaActiveLabel": "Activa",
    "GerenciaVicepresidenciaLabel": "Vicepresidencia",
    "SelectVicepresidenciaPlaceholder": "Seleccione una vicepresidencia",
    "AddGerenciaButton": "Agregar Gerencia",
    "EditGerenciaButton": "Editar Gerencia",
    "DeleteGerenciaButton": "Eliminar Gerencia",
    "LoadingGerencias": "Cargando gerencias...",
    "NoGerenciasFound": "No se encontraron gerencias.",
    "GerenciaLabel": "Gerencia",

    // Mantenedor Usuarios
    "AddUserButton": "Nuevo Usuario",
    "EditUserButton": "Editar Usuario",
    "DeleteUserButton": "Eliminar Usuario",
    "UserLabel": "Usuario",
    "EmailLabel": "Email",
    "ConfirmDeleteUser": "¿Está seguro que desea eliminar el usuario {0}?",
    "UserDeletedSuccess": "Usuario eliminado correctamente.",
    "ErrorDeletingUser": "Error al eliminar el usuario.",
    "UserUpdatedSuccess": "Usuario actualizado correctamente.",
    "ErrorUpdatingUser": "Error al actualizar el usuario.",
    "UserAddedSuccess": "Usuario agregado correctamente.",
    "ErrorAddingUser": "Error al agregar el usuario.",
    "LoadingUsers": "Cargando usuarios...",
    "ErrorFetchingData": "Error al cargar los datos.",
    "SelectGerenciaPlaceholder": "Seleccione una gerencia...",
    "UsuarioDeletedSuccess": "Usuario eliminado correctamente.",
    "ErrorDeletingUsuario": "Error al eliminar el usuario.",
    "ErrorUpdatingUsuario": "Error al actualizar el usuario.",
    "ErrorAddingUsuario": "Error al agregar el usuario.",
    "UsuarioUpdatedSuccess": "Usuario actualizado correctamente.",
    "UsuarioAddedSuccess": "Usuario agregado correctamente.",
    "UsuarioDeleteButton": "Eliminar Usuario", 
    "UsuarioActivoLabel": "Acitvo",
    "GerenciaLabel": "Gerencia",
    "DivisionLabel": "División",
    "GerenciaVicepresidenciaLabel": "Vicepresidencia",
    "SelectDivisionPlaceholder": "Seleccione una división",
    "UsuarioROLLabel": "ROL",
    "SelectDivisionFilterPlaceholder": "Filtrar por División",

    // Mantenedor Divisiones
    "MantenedorDivisionesView": "Mantenedor de Divisiones",
    "ErrorFetchingDivisiones": "Error al cargar las divisiones.",
    "ConfirmDeleteDivision": "¿Está seguro que desea eliminar la división {0}?",
    "DivisionDeletedSuccess": "División eliminada con éxito.",
    "ErrorDeletingDivision": "No se pudo eliminar la división.",
    "ErrorUpdatingDivision": "Error al actualizar la división.",
    "ErrorAddingDivision": "Error al agregar la división.",
    "DivisionUpdatedSuccess": "División actualizada con éxito.",
    "DivisionAddedSuccess": "División agregada con éxito.",
    "CannotDeleteDivisionWithoutId": "No se puede eliminar una división sin ID.",
    "DivisionNameLabel": "Nombre de la División",
    "DivisionActiveLabel": "Activa",
    "AddDivisionButton": "Agregar División",
    "EditDivisionButton": "Editar División",
    "DeleteDivisionButton": "Eliminar División",
    "LoadingDivisiones": "Cargando divisiones...",
    "NoDivisionesFound": "No se encontraron divisiones.",

    // Mantenedor Horarios
    "MantenedorHorariosTitle": "Mantenedor de Horarios",
    "AddHoraButton": "Agregar Hora",
    "EditHoraButton": "Editar Hora",
    "DeleteHoraButton": "Eliminar Hora",
    "HoraNameLabel": "Hora",
    "LoadingHoras": "Cargando horarios...",
    "NoHorasFound": "No se encontraron horarios.",
    "ConfirmDeleteHora": "¿Está seguro que desea eliminar la hora {0}?",
    "ErrorFetchingHoras": "Error al cargar los horarios.",
    "ErrorAddingHora": "Error al agregar la hora.",
    "ErrorUpdatingHora": "Error al actualizar la hora.",
    "ErrorDeletingHora": "Error al eliminar la hora.",
    "CannotDeleteHoraWithoutId": "No se puede eliminar una hora sin ID.",
    "HourLabel": "Hora",
    "MinuteLabel": "Minuto",
    "AMLabel": "AM",
    "PMLabel": "PM",
    "InvalidTimeFormat": "Formato de hora inválido.",
    "SelectHourPlaceholder": "Seleccione hora",
    "SelectMinutePlaceholder": "Seleccione minuto",
    "SelectAMPMPlaceholder": "AM/PM",
    "TimeFormatError": "Formato de hora inválido. Por favor use HH:MM AM/PM.",
    "HoraUpdatedSuccess": "Hora actualizada con éxito.",
    "HoraAddedSuccess": "Hora agregada con éxito.",
    "HoraDeletedSuccess": "Hora eliminada con éxito.",

    // GenerarQR.tsx
    "GenerarQRTitle": "Generar QR",
    "GenerarQRMissingSelection": "Por favor seleccione una División, Piso y Sala (para QR individual) o División y Piso (para QR masivo).",
    "GenerarQRInvalidSelection": "Selección inválida. Por favor asegúrese de que la División, Piso y Sala seleccionados existen.",
    "GenerarQRNoRoomsFound": "No se encontraron salas para el piso seleccionado.",
    "GenerarQRIndividualButton": "Generar QR Individual",
    "GenerarQRMassiveButton": "Generar QR Masivo",
    "GenerarQRButton": "Generar QR",
    "GuardarQRButton": "Guardar QR",
    "GenerarQRIndividualResult": "",
    "guardarQRSuccessMessage": "QR guardado exitosamente.",
    "GenerarQRMassiveResult": "",
    "SalaLabel": "Sala",
    "SelectSalaPlaceholder": "Seleccione una Sala",

    //MantenedorPisos 
    "ConfirmDeletePiso": "¿Está seguro que desea eliminar el piso {0}?",
    "PisoDeletedSuccess": "Piso eliminado con éxito. ",
    "ErrorDeletingPiso": "No se pudo eliminar el piso. ",
    "ErrorUpdatingPiso": "Error al actualizar el piso. ",
    "ErrorAddingPiso": "Error al agregar el piso. ",
    "CannotDeletePisoWithoutId": "No se puede eliminar un piso sin ID. ",
    "PisoNameLabel": "Nombre del Piso",
    "PisoPlantaLabel": "División",
    "PisoActiveLabel": "Activo",
    "AddPisoButton": "Agregar Piso",
    "EditPisoButton": "Editar Piso",
    "DeletePisoButton": "Eliminar Piso",
    "LoadingPisos": "Cargando pisos...",
    "NoPisosFound": "No se encontraron pisos.",
    "PisoSavedSuccessfully": "Piso guardado exitosamente.",
    "PisoEditedSuccessfully": "Piso editado exitosamente."
  }
});