declare interface ISrscWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
  camposObligatoriosTitle: string;

  // Srsc.tsx
  ReservaSalaView: string;
  SalasDisponiblesView: string;
  BloqueoSalaView: string;
  GenerarQRView: string;
  ReportesView: string;
  MisReservasView: string;

  // ReservaSala.tsx
  ReservaSalaTitle: string;
  LoadingConfig: string;
  PlantaLabel: string;
  SelectPlantaPlaceholder: string;
  PisoLabel: string;
  SelectPisoPlaceholder: string;
  UsuarioLabel: string;
  SelectUsuarioPlaceholder: string;
  FechaReservaLabel: string;
  SelectFechaReservaPlaceholder: string;
  PlanoPisoTitle: string;
  SelectPlantaPisoFechaAvailability: string;
  ViewHorariosFor: string;
  SelectPlantaPisoFechaSalaWarning: string;
  ErrorLoadingFilterOptions: string;
  ErrorLoadingSalasForPiso: string;
  ErrorLoadingHorariosForSala: string;
  MissingReservationData: string;
  ReservationConfirmedSuccess: string;
  ReservationConfirmError: string;

  // SalasDisponibles.tsx
  SalasDisponiblesTitle: string;
  LoadingFilters: string;
  NoAvailableRoomsForDate: string;
  NoPisosConfiguredForPlanta: string;
  SelectPlantaToViewPisos: string;
  PisoColumn: string;
  SalaColumn: string;
  CapacidadColumn: string;
  HorasDisponiblesColumn: string;
  AccionesColumn: string;
  ViewDetailAndReserveRoom: string;
  ReserveButton: string;
  SelectPlantaUsuarioFechaReserveWarning: string;
  ErrorLoadingAvailableRoomsForPiso: string;
  LoadingSalasFor: string;

  // BloqueoSala.tsx
  BloqueoSalaTitle: string;
  FechaBloqueoLabel: string;
  SelectFechaBloqueoPlaceholder: string;
  SelectPlantaPisoUsuarioFechaBlockWarning: string;
  BlockRoom: string;
  ConfirmBloqueoSalaTitle: string;
  ComentarioBloqueoLabel: string;
  ComentarioBloqueoPlaceholder: string;
  ConfirmBloqueoButton: string;
  CancelButton: string;
  CompleteAllFieldsBlockWarning: string;
  RoomBlockedSuccess: string;
  RoomBlockError: string;

  // ReservaSalaSchedule.tsx
  ReservationDetailsTitle: string;
  FechaNotSelected: string;
  LoadingHorarios: string;
  NoHorariosAvailable: string;
  HorasDisponiblesTable: string;
  DisponibilidadTable: string;
  ReservadoPorTable: string;
  ReservedStatus: string;
  NotAvailableStatus: string;
  NoReservationStatus: string;
  AvailableStatus: string;
  NAStatus: string;
  AsistentesPeoplePicker: string;
  ConfirmReservationButton: string;
  CloseButton: string;

//MisReservas.tsx

  MisReservasTitle: string;
  ReservaEliminadaSuccess: string;
  ReservaEliminadaError: string;
  DeleteReservationButton: string;

  // Reportes.tsx
  ReportesTitle: string;
  AllPlaceholder: string;
  FechaDesdeLabel: string;
  FechaHastaLabel: string;
  SearchButton: string;
  ExportToCSVButton: string;
  ErrorLoadingReport: string;
  LoadingReport: string;
  NoResultsFound: string;
  SalaReservadaColumn: string;
  FechaReservaColumn: string;
  FechaTerminoReservaColumn: string;
  BloqueHorarioColumn: string;
  EstadoColumn: string;
  FechaCheckInColumn: string;
  FechaCheckOutColumn: string;
  KPIColumn: string;
  VerColumn: string;
  EliminarColumn: string;
  ViewDetailsButton: string;

  // Mantenedores
  MantenedorView: string;
  MantenedorHorariosView: string;
  MantenedorUsuariosView: string;
  MantenedorSalasView: string;
  MantenedorPisosView: string;
  MantenedorVicepresidenciasView: string;

  // MantenedorSalas.tsx
  MantenedorSalasTitle: string;
  AddSalaButton: string;
  EditSalaButton: string;
  VerQR:  string;
  DeleteSalaButton: string;
  SalaNameLabel: string;
  SalaCupoLabel: string;
  SalaPisoLabel: string;
  SalaCoordinatesLabel: string;
  SalaActiveLabel: string;
  SelectPisoFilterPlaceholder: string;
  SelectPlantaFilterPlaceholder: string;
  CannotDeleteSalaWithoutId: string;
  NoSalasFound: string;
  ConfirmDeleteSala: string;
  SalaAddedSuccess: string;
  SalaUpdatedSuccess: string;
  SalaDeletedSuccess: string;
  ErrorAddingSala: string;
  ErrorUpdatingSala: string;
  ErrorDeletingSala: string;
  ErrorFetchingSalas: string;
  ErrorFetchingPisos: string;
  LoadingSalas: string;
  LoadingPisos: string;
  SaveButton: string;
  RequiredField: string;
  InvalidNumber: string;
  InvalidCoordinates: string;
  HorariosLabel: string;
  SelectAllHorasLabel: string;

  // Mantenedor Vicepresidencias
  MantenedorVicepresidenciasView: string;
  ErrorFetchingVicepresidencias: string;
  ConfirmDeleteVicepresidencia: string;
  VicepresidenciaDeletedSuccess: string;
  ErrorDeletingVicepresidencia: string;
  FormErrorsWarning: string;
  VicepresidenciaUpdatedSuccess: string;
  VicepresidenciaAddedSuccess: string;
  ErrorUpdatingVicepresidencia: string;
  ErrorAddingVicepresidencia: string;
  CannotDeleteWithoutId: string;
  VicepresidenciaNameLabel: string;
  VicepresidenciaActiveLabel: string;
  YesLabel: string;
  NoLabel: string;
  EditVicepresidenciaButton: string;
  DeleteVicepresidenciaButton: string;
  AddVicepresidenciaButton: string;
  LoadingVicepresidencias: string;
  NoVicepresidenciasFound: string;

  // Mantenedor Gerencia
  MantenedorGerenciaView: string;
  ErrorFetchingGerencias: string;
  ConfirmDeleteGerencia: string;
  GerenciaDeletedSuccess: string;
  ErrorDeletingGerencia: string;
  ErrorUpdatingGerencia: string;
  ErrorAddingGerencia: string;
  GerenciaUpdatedSuccess: string;
  GerenciaAddedSuccess: string;
  CannotDeleteGerenciaWithoutId: string;
  GerenciaNameLabel: string;
  GerenciaLabel: string;
  GerenciaActiveLabel: string;
  GerenciaVicepresidenciaLabel: string;
  SelectVicepresidenciaPlaceholder: string;
  AddGerenciaButton: string;
  EditGerenciaButton: string;
  DeleteGerenciaButton: string;
  LoadingGerencias: string;
  NoGerenciasFound: string;

  // Mantenedor Usuarios
  AddUserButton: string;
  EditUserButton: string;
  DeleteUserButton: string;
  UserLabel: string;
  EmailLabel: string;
  ConfirmDeleteUser: string;
  UserDeletedSuccess: string;
  ErrorDeletingUser: string;
  UserUpdatedSuccess: string;
  ErrorUpdatingUser: string;
  UserAddedSuccess: string;
  ErrorAddingUser: string;
  LoadingUsers: string;
  ErrorFetchingData: string;
  SelectGerenciaPlaceholder: string;
  UsuarioDeletedSuccess: string;
  ErrorDeletingUsuario: string;
  ErrorUpdatingUsuario: string;
  ErrorAddingUsuario: string;
  UsuarioUpdatedSuccess: string;
  UsuarioAddedSuccess: string;
  UsuarioDeleteButton: string;
  UsuarioActivoLabel: string;
  GerenciaLabel: string;
  DivisionLabel: string;
  GerenciaVicepresidenciaLabel: string;
  SelectDivisionPlaceholder: string;
  UsuarioROLLabel: string;
  SelectDivisionFilterPlaceholder: string;

  // Mantenedor Divisiones
  MantenedorDivisionesView: string;
  ErrorFetchingDivisiones: string;
  ConfirmDeleteDivision: string;
  DivisionDeletedSuccess: string;
  ErrorDeletingDivision: string;
  ErrorUpdatingDivision: string;
  ErrorAddingDivision: string;
  DivisionUpdatedSuccess: string;
  DivisionAddedSuccess: string;
  CannotDeleteDivisionWithoutId: string;
  DivisionNameLabel: string;
  DivisionActiveLabel: string;
  AddDivisionButton: string;
  EditDivisionButton: string;
  DeleteDivisionButton: string;
  LoadingDivisiones: string;
  NoDivisionesFound: string;

  // Mantenedor Horarios
  MantenedorHorariosTitle: string;
  AddHoraButton: string;
  EditHoraButton: string;
  DeleteHoraButton: string;
  HoraNameLabel: string;
  LoadingHoras: string;
  NoHorasFound: string;
  HoraDeletedSuccess: string;
  HoraAddedSuccess: string;
  HoraUpdatedSuccess: string;
  ConfirmDeleteHora: string;
  ErrorFetchingHoras: string;
  ErrorAddingHora: string;
  ErrorUpdatingHora: string;
  ErrorDeletingHora: string;
  CannotDeleteHoraWithoutId: string;
  HourLabel: string;
  MinuteLabel: string;
  AMLabel: string;
  PMLabel: string;
  InvalidTimeFormat: string;
  SelectHourPlaceholder: string;
  SelectMinutePlaceholder: string;
  SelectAMPMPlaceholder: string;
  TimeFormatError: string;

  // GenerarQR.tsx
  GenerarQRTitle: string;
  GenerarQRMissingSelection: string;
  GenerarQRInvalidSelection: string;
  GenerarQRNoRoomsFound: string;
  GenerarQRIndividualButton: string;
  GenerarQRMassiveButton: string;
  GenerarQRButton: string;
  GuardarQRButton: string;
  guardarQRSuccessMessage: string;
  GenerarQRIndividualResult: string;
  GenerarQRMassiveResult: string;
  SalaLabel: string;
  SelectSalaPlaceholder: string;

  // MantenedorPisos.tsx
  MantenedorPisosTitle: string;
  AddPisoButton: string;
  EditPisoButton: string;
  DeletePisoButton: string;
  PisoNameLabel: string;
  PisoPlantaLabel: string;
  PisoActiveLabel: string;
  SelectPlantaForPisoPlaceholder: string;
  ConfirmDeletePiso: string;
  PisoDeletedSuccess: string;
  ErrorDeletingPiso: string;
  ErrorUpdatingPiso: string;
  ErrorAddingPiso: string;
  CannotDeletePisoWithoutId: string;
  PisoUpdatedSuccess: string;
  PisoAddedSuccess: string;
  LoadingPisos: string;
  NoPisosFound: string;
  PisoSavedSuccessfully: string;
  PisoEditedSuccessfully: string;
}

declare module 'SrscWebPartStrings' {
  const strings: ISrscWebPartStrings;
  export = strings;
}
